// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: library.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	CheckBooks(ctx context.Context, opts ...grpc.CallOption) (BookService_CheckBooksClient, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) CheckBooks(ctx context.Context, opts ...grpc.CallOption) (BookService_CheckBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], "/library.BookService/CheckBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceCheckBooksClient{stream}
	return x, nil
}

type BookService_CheckBooksClient interface {
	Send(*BookRequest) error
	Recv() (*BookResponse, error)
	grpc.ClientStream
}

type bookServiceCheckBooksClient struct {
	grpc.ClientStream
}

func (x *bookServiceCheckBooksClient) Send(m *BookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bookServiceCheckBooksClient) Recv() (*BookResponse, error) {
	m := new(BookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	CheckBooks(BookService_CheckBooksServer) error
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) CheckBooks(BookService_CheckBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckBooks not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_CheckBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).CheckBooks(&bookServiceCheckBooksServer{stream})
}

type BookService_CheckBooksServer interface {
	Send(*BookResponse) error
	Recv() (*BookRequest, error)
	grpc.ServerStream
}

type bookServiceCheckBooksServer struct {
	grpc.ServerStream
}

func (x *bookServiceCheckBooksServer) Send(m *BookResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bookServiceCheckBooksServer) Recv() (*BookRequest, error) {
	m := new(BookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "library.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckBooks",
			Handler:       _BookService_CheckBooks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "library.proto",
}
