name: execute-cmd
on: [push]
jobs:
  run-cmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc 
      - run: ./library/cmd.sh